services:
  backend:
    image: mysite:backend
    container_name: mysite-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    image: mysite:frontend
    pull_policy: never
    container_name: mysite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  mongodb:
    image: mongo:7.0.12
    container_name: Docker-mongodb
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./mongodb/.env

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    container_name: mysite.mongo-express
    env_file:
      - ./mongo-express/.env

volumes:
  mongodb_data:
